In [1]:
import pandas as pd
import numpy as np

In [2]:
all_data = pd.read_csv('Open-Close Price Long Format.csv')

In [3]:
all_data_copy = all_data.pivot_table(index=['Ticker','Date'],columns=['Type'],values='Price').reset_index()
all_data_copy['Prev Close'] = all_data_copy.groupby(['Ticker'])['Close'].shift()
all_data_copy.dropna(inplace=True)
all_data_copy['Open Gap'] = all_data_copy['Open']-all_data_copy['Prev Close']
all_data_copy['Current Day Return'] = all_data_copy['Close']/all_data_copy['Open']-1

all_data_copy['Date'] = all_data_copy['Date'].apply(lambda x: x[:10])

In [4]:
all_data_copy.head(10)

Type,Ticker,Date,Close,Open,Prev Close,Open Gap,Current Day Return
1,AAPL,2010-01-05,7.656429,7.664286,7.643214,0.021072,-0.001025
2,AAPL,2010-01-06,7.534643,7.656429,7.656429,0.000000,-0.015906
3,AAPL,2010-01-07,7.520714,7.562500,7.534643,0.027857,-0.005525
4,AAPL,2010-01-08,7.570714,7.510714,7.520714,-0.010000,0.007989
5,AAPL,2010-01-11,7.503929,7.600000,7.570714,0.029286,-0.012641
6,AAPL,2010-01-12,7.418571,7.471071,7.503929,-0.032858,-0.007027
7,AAPL,2010-01-13,7.523214,7.423929,7.418571,0.005358,0.013374
8,AAPL,2010-01-14,7.479643,7.503929,7.523214,-0.019285,-0.003236
9,AAPL,2010-01-15,7.354643,7.533214,7.479643,0.053571,-0.023705
10,AAPL,2010-01-19,7.680000,7.440357,7.354643,0.085714,0.032208

In [7]:
all_data_copy2 = all_data_copy.pivot_table(index = 'Date',
                                           columns = 'Ticker',
                                           values = ['Open Gap','Current Day Return'])

In [8]:
all_data_copy2

Type       Current Day Return                                          \
Ticker                   AAPL      ABBV       ABT       AMD      AMZN
Date
2010-01-05          -0.001025       NaN -0.008261  0.000000  0.009443
2010-01-06          -0.015906       NaN  0.007045 -0.011364 -0.017459
2010-01-07          -0.005525       NaN  0.008470 -0.004206 -0.015226
2010-01-08           0.007989       NaN  0.005296  0.006403  0.022672
2010-01-11          -0.012641       NaN  0.000543 -0.025586 -0.017418
...                       ...       ...       ...       ...       ...
2022-12-23           0.007180 -0.001775  0.004737  0.022342  0.024024
2022-12-27          -0.010276 -0.003058  0.002030 -0.009394 -0.022714
2022-12-28          -0.027994 -0.008980 -0.010915  0.000480 -0.011836
2022-12-29           0.012657 -0.002455  0.014345  0.018542  0.015808
2022-12-30           0.011837 -0.003822 -0.000091  0.015681  0.010587

Type                                                          ...  Open Gap  \
Ticker           BAC       BMY         C       CCL      CSCO  ...       TJX
Date                                                          ...
2010-01-05  0.029225 -0.010976  0.032164  0.002788 -0.000813  ... -0.030001
2010-01-06  0.011104  0.001986  0.022472 -0.015485 -0.004890  ...  0.010000
2010-01-07  0.014988  0.002383 -0.010840  0.000623  0.009465  ...  0.397500
2010-01-08 -0.011778 -0.018972 -0.016438  0.012188  0.011485  ... -0.185000
2010-01-11 -0.003531  0.005613 -0.008197 -0.005061 -0.002029  ...  0.065001
...              ...       ...       ...       ...       ...  ...       ...
2022-12-23  0.002160 -0.011661  0.005909 -0.006361  0.004868  ... -0.059998
2022-12-27  0.000923 -0.007789  0.002484 -0.014139 -0.002937  ...  0.150002
2022-12-28  0.006141 -0.012076  0.004276 -0.005188 -0.013001  ... -0.070000
2022-12-29  0.007601 -0.002766  0.007136  0.045278  0.005078  ...  0.439995
2022-12-30  0.000604 -0.002495  0.006677  0.010025  0.007827  ... -0.419998

Type                                                                    \
Ticker          TSLA       USB         V      VICI      VTRS        VZ
Date
2010-01-05       NaN -0.119999 -0.209999       NaN -0.269999  0.084410
2010-01-06       NaN -0.029999 -0.029999       NaN -0.150000 -0.656521
2010-01-07       NaN -0.070000  0.002501       NaN -0.150000  0.168821
2010-01-08       NaN -0.200001  0.014999       NaN -0.330000 -0.065653
2010-01-11       NaN  0.290001  0.127501       NaN  0.020000  0.206335
...              ...       ...       ...       ...       ...       ...
2022-12-23  1.020004 -0.019997 -0.929993 -0.049999 -0.030000  0.000000
2022-12-27 -5.650002  0.149998  0.089996  0.030003  0.020000  0.080002
2022-12-28  1.250000  0.070000  0.389999  0.049999  0.000000 -0.060001
2022-12-29  7.680000 -0.379997  0.959991  0.190002 -0.050000  0.090000
2022-12-30 -1.870003 -0.169998 -1.750000 -0.209999 -0.040000  0.050003

Type
Ticker           WFC       WMB       XOM
Date
2010-01-05 -0.049999 -0.081520  0.040001
2010-01-06 -0.039999  0.073368  0.029999
2010-01-07  0.010000 -0.024456 -0.119995
2010-01-08 -0.230000 -0.016304 -0.110001
2010-01-11  0.230000  0.089672  0.420006
...              ...       ...       ...
2022-12-23  0.009998  0.099998  1.070000
2022-12-27  0.029999  0.070000  0.589996
2022-12-28 -0.100002 -0.070000 -0.279999
2022-12-29  0.030003 -0.070000 -0.389999
2022-12-30 -0.220001 -0.120003 -0.589996

[3271 rows x 102 columns]

In [34]:
signal = all_data_copy2['Open Gap'].rolling(101).rank(method='max')>99
signal = pd.DataFrame(signal.stack(),columns=['Signal'])

In [42]:
signal = signal.loc[signal['Signal']==True]

In [50]:
pnl = pd.DataFrame(all_data_copy2['Current Day Return'].stack(),columns=['Current Day Return']).loc[signal.index]

In [56]:
pnl.mean()/pnl.std()

Current Day Return    0.021085
dtype: float64

In [55]:
len(pnl.loc[pnl['Current Day Return']>0])/len(pnl)

0.5120071153276016

In [61]:
pnl.mean()

Current Day Return    0.000525
dtype: float64

In [ ]:
# sharpe
# per trade returns
# hit ratio (positive return/all) golden is >52%